# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    #    allowed_methods_listener:  true
    routing_loader: false
    view:
        view_response_listener:  true
    #    exception:
    #        codes:
    #            App\Exception\MyException: 403
    #        messages:
    #            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/api/internal, fallback_format: json, priorities: [ json ] }
            - { path: ^/, fallback_format: html, priorities: [ html, json ] }
    serializer:
        serialize_null: true
    body_listener:
        enabled: true
