knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_ID)%'
            client_secret: '%env(GOOGLE_SECRET)%'
            redirect_route: oauth_check
            redirect_params:
                service: google
        linkedin:
            type: linkedin
            client_id: '%env(LINKEDIN_ID)%'
            client_secret: '%env(LINKEDIN_SECRET)%'
            redirect_route: oauth_check
            redirect_params:
                service: linkedin
        microsoft:
            type: microsoft
            client_id: '%env(MICROSOFT_ID)%'
            client_secret: '%env(MICROSOFT_SECRET)%'
            redirect_route: oauth_check
            redirect_params:
                service: microsoft
        facebook:
            type: facebook
            client_id: '%env(OAUTH_FACEBOOK_ID)%'
            client_secret: '%env(OAUTH_FACEBOOK_SECRET)%'
            redirect_route: oauth_check
            redirect_params:
                service: facebook
            graph_api_version: v2.12
